In [1]:
import sqlite3
import pandas as pd

con=sqlite3.connect(r"C:\Users\muham\Works\project 3.1\Data\raw\ipl.db")
def q(sql):
    return pd.read_sql_query(sql,con)

In [2]:
q("select * from venues;")

,venue_id,venue,city
0,1,M Chinnaswamy Stadium,Bangalore
1,2,"Rajiv Gandhi International Stadium, Uppal",Hyderabad
2,3,Maharashtra Cricket Association Stadium,Pune
3,4,Saurashtra Cricket Association Stadium,Rajkot
4,5,Holkar Cricket Stadium,Indore
...,...,...,...
58,59,Subrata Roy Sahara Stadium,Pune
59,60,Shaheed Veer Narayan Singh International Stadium,Raipur
60,61,JSCA International Stadium Complex,Ranchi
61,62,Maharaja Yadavindra Singh International Cricke...,New Chandigarh
62,63,Maharaja Yadavindra Singh International Cricke...,New Chandigarh

In [3]:
q("select * from matches;")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,Royal Challengers Bangalore,NaN,9.0,win,JR Hazlewood,252,1,1,1,4664.0
1208,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Rajasthan Royals,NaN,6.0,win,D Ferreira,494,134,134,134,11389.0
1209,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,6.0,win,H Klaasen,3,2,3,2,1740.0
1210,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,Gujarat Titans,NaN,4.0,win,JO Holder,1,615,615,615,4098.0
1211,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,Delhi Capitals,NaN,7.0,win,KL Rahul,134,252,134,252,1409.0

In [4]:
q("select match_id,season_id,city,match_winner from matches where match_winner = 'Chennai Super Kings';")

     match_id  season_id       city         match_winner
0     1136561       2018     Mumbai  Chennai Super Kings
1     1136565       2018    Chennai  Chennai Super Kings
2     1136577       2018       Pune  Chennai Super Kings
3     1136580       2018  Hyderabad  Chennai Super Kings
4     1136584       2018  Bengaluru  Chennai Super Kings
..        ...        ...        ...                  ...
141   1473494       2025    Kolkata  Chennai Super Kings
142   1473504       2025  Ahmedabad  Chennai Super Kings
143   1527691       2026    Chennai  Chennai Super Kings
144   1529265       2026    Chennai  Chennai Super Kings
145   1529276       2026     Mumbai  Chennai Super Kings

[146 rows x 4 columns]

In [5]:
q("""select match_id,season,city,venue
from matches 
where season >= 2015;""")

,match_id,season,city,venue
0,829705,2015,Kolkata,Eden Gardens
1,829707,2015,Chennai,"MA Chidambaram Stadium, Chepauk"
2,829709,2015,Pune,Maharashtra Cricket Association Stadium
3,829711,2015,Chennai,"MA Chidambaram Stadium, Chepauk"
4,829713,2015,Kolkata,Eden Gardens
...,...,...,...,...
749,1529282,2026,Delhi,"Arun Jaitley Stadium, Delhi"
750,1529283,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
751,1529284,2026,Mumbai,"Wankhede Stadium, Mumbai"
752,1529285,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
753,1529286,2026,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [6]:
q("""select match_id,season,city,venue
from matches
where season >= 2015 or city = "Bangalore";""")

,match_id,season,city,venue
0,335982,2008,Bangalore,M Chinnaswamy Stadium
1,1082591,2017,Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
2,1082592,2017,Pune,Maharashtra Cricket Association Stadium
3,1082593,2017,Rajkot,Saurashtra Cricket Association Stadium
4,1082594,2017,Indore,Holkar Cricket Stadium
...,...,...,...,...
791,1529282,2026,Delhi,"Arun Jaitley Stadium, Delhi"
792,1529283,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
793,1529284,2026,Mumbai,"Wankhede Stadium, Mumbai"
794,1529285,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
795,1529286,2026,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [7]:
q("""select match_id,season,city,venue
from matches
where season >= 2015 and city = "Bangalore";""")

    match_id season       city                  venue
0     829719   2015  Bangalore  M Chinnaswamy Stadium
1     829737   2015  Bangalore  M Chinnaswamy Stadium
2     829745   2015  Bangalore  M Chinnaswamy Stadium
3     829763   2015  Bangalore  M Chinnaswamy Stadium
4     829771   2015  Bangalore  M Chinnaswamy Stadium
5     829785   2015  Bangalore  M Chinnaswamy Stadium
6     829813   2015  Bangalore  M Chinnaswamy Stadium
7     980907   2016  Bangalore  M Chinnaswamy Stadium
8     980921   2016  Bangalore  M Chinnaswamy Stadium
9     980959   2016  Bangalore  M Chinnaswamy Stadium
10    980969   2016  Bangalore  M Chinnaswamy Stadium
11    980981   2016  Bangalore  M Chinnaswamy Stadium
12    980987   2016  Bangalore  M Chinnaswamy Stadium
13    980999   2016  Bangalore  M Chinnaswamy Stadium
14    981013   2016  Bangalore  M Chinnaswamy Stadium
15    981019   2016  Bangalore  M Chinnaswamy Stadium
16   1082602   2017  Bangalore  M Chinnaswamy Stadium
17   1082607   2017  Bangalore  M Chinnaswamy Stadium
18   1082621   2017  Bangalore  M Chinnaswamy Stadium
19   1082633   2017  Bangalore  M Chinnaswamy Stadium
20   1082636   2017  Bangalore  M Chinnaswamy Stadium
21   1082648   2017  Bangalore  M Chinnaswamy Stadium
22   1082649   2017  Bangalore  M Chinnaswamy Stadium

In [8]:
q("""select season,match_winner 
  from matches
  where season >=2010 and match_winner = "Royal Challengers Bangalore";""")

    season                 match_winner
0     2010  Royal Challengers Bangalore
1     2010  Royal Challengers Bangalore
2     2010  Royal Challengers Bangalore
3     2010  Royal Challengers Bangalore
4     2010  Royal Challengers Bangalore
..     ...                          ...
121   2026  Royal Challengers Bangalore
122   2026  Royal Challengers Bangalore
123   2026  Royal Challengers Bangalore
124   2026  Royal Challengers Bangalore
125   2026  Royal Challengers Bangalore

[126 rows x 2 columns]

In [9]:
q("""select match_id,season,city,venue
from matches 
where season >= 2015 or city = "bangalore"
order by match_id desc""")

,match_id,season,city,venue
0,1529286,2026,Jaipur,"Sawai Mansingh Stadium, Jaipur"
1,1529285,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
2,1529284,2026,Mumbai,"Wankhede Stadium, Mumbai"
3,1529283,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
4,1529282,2026,Delhi,"Arun Jaitley Stadium, Delhi"
...,...,...,...,...
749,829713,2015,Kolkata,Eden Gardens
750,829711,2015,Chennai,"MA Chidambaram Stadium, Chepauk"
751,829709,2015,Pune,Maharashtra Cricket Association Stadium
752,829707,2015,Chennai,"MA Chidambaram Stadium, Chepauk"
753,829705,2015,Kolkata,Eden Gardens

In [10]:
q("""select match_id,season,city,venue
from matches 
where season >= 2015 or city = "bangalore"
order by match_id asc""")

,match_id,season,city,venue
0,829705,2015,Kolkata,Eden Gardens
1,829707,2015,Chennai,"MA Chidambaram Stadium, Chepauk"
2,829709,2015,Pune,Maharashtra Cricket Association Stadium
3,829711,2015,Chennai,"MA Chidambaram Stadium, Chepauk"
4,829713,2015,Kolkata,Eden Gardens
...,...,...,...,...
749,1529282,2026,Delhi,"Arun Jaitley Stadium, Delhi"
750,1529283,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...
751,1529284,2026,Mumbai,"Wankhede Stadium, Mumbai"
752,1529285,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad"
753,1529286,2026,Jaipur,"Sawai Mansingh Stadium, Jaipur"

In [11]:
q("""select count(*) as matches
from matches;""")

   matches
0     1212

In [12]:
q("""select count(*) as deliveries
from deliveries;""")

   deliveries
0      288226

In [13]:
q("""select count(*) as players
from players;""")

   players
0      799

In [14]:
q("""select count(*) as teams
from teams;""")

   teams
0     16

In [15]:
q("""select count(*) as venues
from venues;""")

   venues
0      63

In [16]:
q("""select venue,count(*)as matche_count
from matches
group by venue;""")

                                                venue  matche_count
0                                Arun Jaitley Stadium            14
1                         Arun Jaitley Stadium, Delhi            27
2                                    Barabati Stadium             7
3                 Barsapara Cricket Stadium, Guwahati             8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...            26
5                                   Brabourne Stadium            10
6                           Brabourne Stadium, Mumbai            17
7                                        Buffalo Park             3
8                               De Beers Diamond Oval             3
9                          Dr DY Patil Sports Academy            17
10                 Dr DY Patil Sports Academy, Mumbai            20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...            13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...             4
13                Dubai International Cricket Stadium            46
14                                       Eden Gardens            77
15                              Eden Gardens, Kolkata            27
16                                   Feroz Shah Kotla            60
17                                         Green Park             4
18       Himachal Pradesh Cricket Association Stadium             9
19  Himachal Pradesh Cricket Association Stadium, ...             6
20                             Holkar Cricket Stadium             9
21                 JSCA International Stadium Complex             7
22                                          Kingsmead            15
23                              M Chinnaswamy Stadium            65
24                   M Chinnaswamy Stadium, Bengaluru            24
25                              M.Chinnaswamy Stadium            15
26                             MA Chidambaram Stadium             9
27                    MA Chidambaram Stadium, Chepauk            48
28           MA Chidambaram Stadium, Chepauk, Chennai            38
29  Maharaja Yadavindra Singh International Cricke...            10
30  Maharaja Yadavindra Singh International Cricke...             5
31            Maharashtra Cricket Association Stadium            22
32      Maharashtra Cricket Association Stadium, Pune            13
33                   Narendra Modi Stadium, Ahmedabad            37
34                                      Nehru Stadium             5
35                              New Wanderers Stadium             8
36                                           Newlands             7
37                                    OUTsurance Oval             2
38       Punjab Cricket Association IS Bindra Stadium            10
39  Punjab Cricket Association IS Bindra Stadium, ...            11
40  Punjab Cricket Association IS Bindra Stadium, ...             5
41         Punjab Cricket Association Stadium, Mohali            35
42                 Rajiv Gandhi International Stadium            15
43          Rajiv Gandhi International Stadium, Uppal            49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...            23
45                       Sardar Patel Stadium, Motera            12
46             Saurashtra Cricket Association Stadium            10
47                             Sawai Mansingh Stadium            47
48                     Sawai Mansingh Stadium, Jaipur            19
49   Shaheed Veer Narayan Singh International Stadium             6
50                            Sharjah Cricket Stadium            28
51                               Sheikh Zayed Stadium            29
52                                   St George's Park             7
53                         Subrata Roy Sahara Stadium            16
54                                    SuperSport Park            12
55       Vidarbha Cricket Association Stadium, Jamtha             3
56                                   Wankhede Stadium            73
57                           Wankhede Stadium, Mumbai            57
58                   Zayed Cricket Stadium, Abu Dhabi             8

In [17]:
q("""select match_winner,count(*)as winner_count
from matches
group by match_winner;""")

                   match_winner  winner_count
0           Chennai Super Kings           146
1                Delhi Capitals           126
2                 Gujarat Lions            13
3                Gujarat Titans            42
4          Kochi Tuskers Kerala             6
5         Kolkata Knight Riders           137
6          Lucknow Super Giants            33
7                Mumbai Indians           155
8                 Pune Warriors            13
9                  Punjab Kings           130
10             Rajasthan Royals           125
11       Rising Pune Supergiant            15
12  Royal Challengers Bangalore           139
13          Sunrisers Hyderabad           132

In [18]:
q("""select match_winner,count(*)as winner_count
from matches
group by match_winner
order by winner_count desc;""")

                   match_winner  winner_count
0                Mumbai Indians           155
1           Chennai Super Kings           146
2   Royal Challengers Bangalore           139
3         Kolkata Knight Riders           137
4           Sunrisers Hyderabad           132
5                  Punjab Kings           130
6                Delhi Capitals           126
7              Rajasthan Royals           125
8                Gujarat Titans            42
9          Lucknow Super Giants            33
10       Rising Pune Supergiant            15
11                Pune Warriors            13
12                Gujarat Lions            13
13         Kochi Tuskers Kerala             6

In [19]:
q("""select match_winner,count(*) as winner
from matches
group by match_winner
having winner >100
order by winner desc;""")

                  match_winner  winner
0               Mumbai Indians     155
1          Chennai Super Kings     146
2  Royal Challengers Bangalore     139
3        Kolkata Knight Riders     137
4          Sunrisers Hyderabad     132
5                 Punjab Kings     130
6               Delhi Capitals     126
7             Rajasthan Royals     125

In [20]:
q("""select bowler,count(*) as balls
from deliveries
group by bowler
having balls>1000
order by balls desc;""")

          bowler  balls
0       R Ashwin   4868
1        B Kumar   4596
2      SP Narine   4586
3      RA Jadeja   4261
4      YS Chahal   4068
..           ...    ...
80     SB Jakati   1101
81      VR Aaron   1065
82    GJ Maxwell   1047
83  JR Hazlewood   1035
84    Noor Ahmad   1008

[85 rows x 2 columns]

In [21]:
q("""select count(*) as nullvalues
from matches 
where city is null;""")

   nullvalues
0          51

In [22]:
q("""select count(*) as nullvalues
from matches 
where city is not null;""")

   nullvalues
0        1161

In [23]:
q("""select count(*) as nullvalues
from matches
where win_by_runs is not null;""")

   nullvalues
0         546

In [24]:
q("""select match_winner,count(*) as win_by_runs
from matches
where win_by_runs is not null
group by match_winner;""")

                   match_winner  win_by_runs
0           Chennai Super Kings           75
1                Delhi Capitals           47
2                 Gujarat Lions            1
3                Gujarat Titans           16
4          Kochi Tuskers Kerala            2
5         Kolkata Knight Riders           57
6          Lucknow Super Giants           20
7                Mumbai Indians           77
8                 Pune Warriors            6
9                  Punjab Kings           57
10             Rajasthan Royals           48
11       Rising Pune Supergiant            7
12  Royal Challengers Bangalore           64
13          Sunrisers Hyderabad           69

In [25]:
q("""select lower(batter)
from deliveries;""")

         lower(batter)
0       a ashish reddy
1       a ashish reddy
2       a ashish reddy
3       a ashish reddy
4       a ashish reddy
...                ...
288221          z khan
288222          z khan
288223          z khan
288224          z khan
288225          z khan

[288226 rows x 1 columns]

In [26]:
q("""select trim   ('        virat kholi rcb       ');""")

  trim   ('        virat kholi rcb       ')
0                           virat kholi rcb

In [27]:
q("""select city,length(city)
from venues;
""")

              city  length(city)
0        Bangalore           9.0
1        Hyderabad           9.0
2             Pune           4.0
3           Rajkot           6.0
4           Indore           6.0
..             ...           ...
58            Pune           4.0
59          Raipur           6.0
60          Ranchi           6.0
61  New Chandigarh          14.0
62  New Chandigarh          14.0

[63 rows x 2 columns]

In [28]:
q("""select match_winner,
case when win_by_runs is null
then 'win by wickets'
else 'win by runs'
end as winning_type 
from matches;
""")

                     match_winner    winning_type
0           Kolkata Knight Riders     win by runs
1             Sunrisers Hyderabad     win by runs
2          Rising Pune Supergiant  win by wickets
3           Kolkata Knight Riders  win by wickets
4                    Punjab Kings  win by wickets
...                           ...             ...
1207  Royal Challengers Bangalore  win by wickets
1208             Rajasthan Royals  win by wickets
1209          Sunrisers Hyderabad  win by wickets
1210               Gujarat Titans  win by wickets
1211               Delhi Capitals  win by wickets

[1212 rows x 2 columns]

In [29]:
q("""select venue,count(*) as matches
from matches
group by venue;""")

                                                venue  matches
0                                Arun Jaitley Stadium       14
1                         Arun Jaitley Stadium, Delhi       27
2                                    Barabati Stadium        7
3                 Barsapara Cricket Stadium, Guwahati        8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26
5                                   Brabourne Stadium       10
6                           Brabourne Stadium, Mumbai       17
7                                        Buffalo Park        3
8                               De Beers Diamond Oval        3
9                          Dr DY Patil Sports Academy       17
10                 Dr DY Patil Sports Academy, Mumbai       20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...       13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...        4
13                Dubai International Cricket Stadium       46
14                                       Eden Gardens       77
15                              Eden Gardens, Kolkata       27
16                                   Feroz Shah Kotla       60
17                                         Green Park        4
18       Himachal Pradesh Cricket Association Stadium        9
19  Himachal Pradesh Cricket Association Stadium, ...        6
20                             Holkar Cricket Stadium        9
21                 JSCA International Stadium Complex        7
22                                          Kingsmead       15
23                              M Chinnaswamy Stadium       65
24                   M Chinnaswamy Stadium, Bengaluru       24
25                              M.Chinnaswamy Stadium       15
26                             MA Chidambaram Stadium        9
27                    MA Chidambaram Stadium, Chepauk       48
28           MA Chidambaram Stadium, Chepauk, Chennai       38
29  Maharaja Yadavindra Singh International Cricke...       10
30  Maharaja Yadavindra Singh International Cricke...        5
31            Maharashtra Cricket Association Stadium       22
32      Maharashtra Cricket Association Stadium, Pune       13
33                   Narendra Modi Stadium, Ahmedabad       37
34                                      Nehru Stadium        5
35                              New Wanderers Stadium        8
36                                           Newlands        7
37                                    OUTsurance Oval        2
38       Punjab Cricket Association IS Bindra Stadium       10
39  Punjab Cricket Association IS Bindra Stadium, ...       11
40  Punjab Cricket Association IS Bindra Stadium, ...        5
41         Punjab Cricket Association Stadium, Mohali       35
42                 Rajiv Gandhi International Stadium       15
43          Rajiv Gandhi International Stadium, Uppal       49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...       23
45                       Sardar Patel Stadium, Motera       12
46             Saurashtra Cricket Association Stadium       10
47                             Sawai Mansingh Stadium       47
48                     Sawai Mansingh Stadium, Jaipur       19
49   Shaheed Veer Narayan Singh International Stadium        6
50                            Sharjah Cricket Stadium       28
51                               Sheikh Zayed Stadium       29
52                                   St George's Park        7
53                         Subrata Roy Sahara Stadium       16
54                                    SuperSport Park       12
55       Vidarbha Cricket Association Stadium, Jamtha        3
56                                   Wankhede Stadium       73
57                           Wankhede Stadium, Mumbai       57
58                   Zayed Cricket Stadium, Abu Dhabi        8

In [30]:
q("""select venue,count(*) as matches 
from matches 
where venue = 'Buffalo Park'
group by venue;""")

          venue  matches
0  Buffalo Park        3

In [31]:
q("""select venue,count(*) as matches
from matches
where venue='Buffalo Park' or venue='Eden Gardens'
group by venue;""")

          venue  matches
0  Buffalo Park        3
1  Eden Gardens       77

In [32]:
q("""select batter,count(*) as delivery
from deliveries
group by batter
order by delivery desc;""")

             batter  delivery
0           V Kohli      6942
1         RG Sharma      5561
2          S Dhawan      5483
3         DA Warner      4849
4         AM Rahane      4259
..              ...       ...
722     Sunny Gupta         1
723          U Kaul         1
724  V Pratap Singh         1
725   Y Prithvi Raj         1
726      YA Abdulla         1

[727 rows x 2 columns]

In [33]:
q("""select match_winner,
case when win_by_runs>50
then 'high runs'
else 'low runs'
end as run
from matches;""")

                     match_winner        run
0           Kolkata Knight Riders  high runs
1             Sunrisers Hyderabad   low runs
2          Rising Pune Supergiant   low runs
3           Kolkata Knight Riders   low runs
4                    Punjab Kings   low runs
...                           ...        ...
1207  Royal Challengers Bangalore   low runs
1208             Rajasthan Royals   low runs
1209          Sunrisers Hyderabad   low runs
1210               Gujarat Titans   low runs
1211               Delhi Capitals   low runs

[1212 rows x 2 columns]

In [34]:
q("""select m.match_id,m.venue
from matches m;""")

      match_id                                              venue
0       335982                              M Chinnaswamy Stadium
1      1082591          Rajiv Gandhi International Stadium, Uppal
2      1082592            Maharashtra Cricket Association Stadium
3      1082593             Saurashtra Cricket Association Stadium
4      1082594                             Holkar Cricket Stadium
...        ...                                                ...
1207   1529282                        Arun Jaitley Stadium, Delhi
1208   1529283  Maharaja Yadavindra Singh International Cricke...
1209   1529284                           Wankhede Stadium, Mumbai
1210   1529285                   Narendra Modi Stadium, Ahmedabad
1211   1529286                     Sawai Mansingh Stadium, Jaipur

[1212 rows x 2 columns]

In [35]:
q("""select m.match_id,m.venue,v.city
from matches m
join venues v on m.venue=v.venue
limit 10;""")

   match_id                                      venue       city
0    335982                      M Chinnaswamy Stadium  Bangalore
1   1082591  Rajiv Gandhi International Stadium, Uppal  Hyderabad
2   1082592    Maharashtra Cricket Association Stadium       Pune
3   1082593     Saurashtra Cricket Association Stadium     Rajkot
4   1082594                     Holkar Cricket Stadium     Indore
5   1082595                      M.Chinnaswamy Stadium  Bengaluru
6   1082596  Rajiv Gandhi International Stadium, Uppal  Hyderabad
7   1082597                           Wankhede Stadium     Mumbai
8   1082598                     Holkar Cricket Stadium     Indore
9   1082599    Maharashtra Cricket Association Stadium       Pune

In [36]:
q("""select d.batter,p.bat_style
from deliveries as d
join players as p on p.player_name=d.batter;""")

            batter       bat_style
0       MN Samuels  Right hand Bat
1       MN Samuels  Right hand Bat
2       MN Samuels  Right hand Bat
3       MN Samuels  Right hand Bat
4       MN Samuels  Right hand Bat
...            ...             ...
288221      N Rana   Left hand Bat
288222      N Rana   Left hand Bat
288223      N Rana   Left hand Bat
288224   SU Parakh   Left hand Bat
288225   SU Parakh   Left hand Bat

[288226 rows x 2 columns]

In [37]:
q("""select venue
from venues
except
select distinct venue
from matches;""")

Empty DataFrame
Columns: [venue]
Index: []

In [38]:
q("""select match_id,innings,over_number,ball_number,count(*)as n
from deliveries
group by match_id,innings,over_number,ball_number
having count(*)>1;""")

Empty DataFrame
Columns: [match_id, innings, over_number, ball_number, n]
Index: []

In [39]:
q("""select count(distinct batter)

from deliveries
where batter not in (select player_name from players);""")

   count(distinct batter)
0                       0

In [40]:
q("""select count(*) as total,
sum(case when city is null then 1 else 0 end) as missing
from matches;""")

   total  missing
0   1212       51

In [41]:
    q("""select count(*) as total,
    sum(case when city is null then 1 else 0 end) as missing
    from venues;""")

   total  missing
0     63        2

In [42]:
q("""select count(*) as total,
sum(case when city is null then 1 else 0 end) as a_null,
sum(case when city = '' then 1 else 0 end) as empty,
sum(case when trim(city) = ''and city<>'' then 1 else 0 end)as spaces
from matches;""")

   total  a_null  empty  spaces
0   1212      51      0       0

In [43]:
q("""select venue,count(*)AS total_matches 
FROM matches GROUP BY Venue Order BY Venue;""")

                                                venue  total_matches
0                                Arun Jaitley Stadium             14
1                         Arun Jaitley Stadium, Delhi             27
2                                    Barabati Stadium              7
3                 Barsapara Cricket Stadium, Guwahati              8
4   Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...             26
5                                   Brabourne Stadium             10
6                           Brabourne Stadium, Mumbai             17
7                                        Buffalo Park              3
8                               De Beers Diamond Oval              3
9                          Dr DY Patil Sports Academy             17
10                 Dr DY Patil Sports Academy, Mumbai             20
11  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...             13
12  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...              4
13                Dubai International Cricket Stadium             46
14                                       Eden Gardens             77
15                              Eden Gardens, Kolkata             27
16                                   Feroz Shah Kotla             60
17                                         Green Park              4
18       Himachal Pradesh Cricket Association Stadium              9
19  Himachal Pradesh Cricket Association Stadium, ...              6
20                             Holkar Cricket Stadium              9
21                 JSCA International Stadium Complex              7
22                                          Kingsmead             15
23                              M Chinnaswamy Stadium             65
24                   M Chinnaswamy Stadium, Bengaluru             24
25                              M.Chinnaswamy Stadium             15
26                             MA Chidambaram Stadium              9
27                    MA Chidambaram Stadium, Chepauk             48
28           MA Chidambaram Stadium, Chepauk, Chennai             38
29  Maharaja Yadavindra Singh International Cricke...             10
30  Maharaja Yadavindra Singh International Cricke...              5
31            Maharashtra Cricket Association Stadium             22
32      Maharashtra Cricket Association Stadium, Pune             13
33                   Narendra Modi Stadium, Ahmedabad             37
34                                      Nehru Stadium              5
35                              New Wanderers Stadium              8
36                                           Newlands              7
37                                    OUTsurance Oval              2
38       Punjab Cricket Association IS Bindra Stadium             10
39  Punjab Cricket Association IS Bindra Stadium, ...             11
40  Punjab Cricket Association IS Bindra Stadium, ...              5
41         Punjab Cricket Association Stadium, Mohali             35
42                 Rajiv Gandhi International Stadium             15
43          Rajiv Gandhi International Stadium, Uppal             49
44  Rajiv Gandhi International Stadium, Uppal, Hyd...             23
45                       Sardar Patel Stadium, Motera             12
46             Saurashtra Cricket Association Stadium             10
47                             Sawai Mansingh Stadium             47
48                     Sawai Mansingh Stadium, Jaipur             19
49   Shaheed Veer Narayan Singh International Stadium              6
50                            Sharjah Cricket Stadium             28
51                               Sheikh Zayed Stadium             29
52                                   St George's Park              7
53                         Subrata Roy Sahara Stadium             16
54                                    SuperSport Park             12
55       Vidarbha Cricket Association Stadium, Jamtha              3
56                                   Wankhede Stadium             73
57                           Wankhede Stadium, Mumbai             57
58                   Zayed Cricket Stadium, Abu Dhabi              8

In [44]:
q("""SELECT COUNT (DISTINCT CASE WHEN INSTR(venue,' ') > 0 THEN TRIM(SUBSTR(venue,1,INSTR(venue,' ')-1)) 
ELSE TRIM(venue) END)AS after_coma
FROM matches;""")

   after_coma
0          41

In [45]:
q("""SELECT COUNT (DISTINCT venue) as distinct_venues from matches;""")

   distinct_venues
0               59

In [46]:
q("""SELECT venue,count(*)AS n
FROM venues
GROUP  BY venue
HAVING count(*)>1;""")

                                               venue  n
0                 Dr DY Patil Sports Academy, Mumbai  2
1                Dubai International Cricket Stadium  2
2  Maharaja Yadavindra Singh International Cricke...  2
3                            Sharjah Cricket Stadium  2

In [47]:
 q("""SELECT team_name,
 (SELECT COUNT(*)FROM  matches m
  WHERE  m.team1=team_name OR m.team2=team_name)AS played
  FROM teams t 
  ORDER BY team_name;""")

                      team_name  played
0           Chennai Super Kings     260
1               Deccan Chargers       0
2                Delhi Capitals     276
3                 Gujarat Lions      30
4                Gujarat Titans      69
5          Kochi Tuskers Kerala      14
6         Kolkata Knight Riders     272
7          Lucknow Super Giants      66
8                Mumbai Indians     285
9                 Pune Warriors      46
10                 Punjab Kings     272
11             Rajasthan Royals     245
12       Rising Pune Supergiant      30
13      Rising Pune Supergiants       0
14  Royal Challengers Bangalore     279
15          Sunrisers Hyderabad     280